export const portfolioData = {
  name: "Sebastián Brizuela",
  title: "Estudiante de Ingeniería Informática",
  availability: "Full-time",
  email: "sebita29@gmail.com",
  phone: "1130410888",
  linkedin: "https://www.linkedin.com/in/sbrizuela/",
  github: "https://github.com/SebaB29",
  description: "Soy estudiante de Ingeniería Informática en la Universidad de Buenos Aires, buscando mi primer empleo como Desarrollador trainee o junior. Estoy interesado en aprender y crecer en el ámbito de la tecnología, y busco un entorno colaborativo para seguir capacitándome.",
  longDescription: "Me desempeño bien en trabajos en equipo y tengo un interés particular en áreas como la ciencia de datos y la ciberseguridad. Estoy abierto a colaborar con profesionales experimentados y aprender de ellos mientras aporto mi dedicación y compromiso.",
  education: [
    {
      degree: "Ingeniería Informática",
      institution: "Universidad de Buenos Aires",
      status: "Cursando actualmente",
    },
    {
      degree: "Bachiller en Ciencias Sociales",
      institution: "Colegio Martín y Omar",
      status: "Egresado",
    },
  ],
  languages: ["Python", "C++", "C", "SQL", "Java", "Rust"],
  tools: ["GIT", "Github", "Gitlab", "Jira", "Trello", "Postman"],
  knowledge: [
    "Programación Orientada a Objetos",
    "Test-Driven Development (TDD)",
    "Debugging",
    "Análisis de Datos",
    "Machine Learning",
    "Scrum",
    "TDA (Pila, Cola, Lista, Árbol, Grafo)",
  ],
  repositories: [
    { name: "MyFiubaGymBro", url: "https://github.com/SebaB29/MyFiubaGymBro", description: "Una aplicación de gestión de gimnasios diseñada para la comunidad de la facultad, enfocada en la organización y seguimiento de rutinas de ejercicio." },
    { name: "ReservasHoteles", url: "https://github.com/SebaB29/ReservasHoteles", description: "Un sistema completo para la gestión de reservas de hoteles, desarrollado con una arquitectura robusta y escalable para manejar múltiples transacciones." },
    { name: "Tetris", url: "https://github.com/SebaB29/Tetris", description: "Una fiel implementación del clásico juego Tetris, desarrollada en C++ con un enfoque en la eficiencia y la jugabilidad." },
    { name: "Snake", url: "https://github.com/SebaB29/Snake", description: "La clásica serpiente que crece al comer, un proyecto para practicar la lógica de juegos y el manejo de estado en tiempo real." },
    { name: "CriticasPeliculas", url: "https://github.com/SebaB29/CriticasPeliculas", description: "Una plataforma interactiva para que los usuarios puedan escribir, compartir y debatir críticas de películas, creando una comunidad de cinéfilos." },
    { name: "Andypolis", url: "https://github.com/SebaB29/Andypolis", description: "Un juego de simulación de construcción y gestión de ciudades, inspirado en los clásicos del género, donde el jugador toma decisiones estratégicas." },
  ],
};
